### ISSUE TITLE
Make Requests on login more efficient

### ISSUE THREAD

**Issue by OverlordsIII** [Elephant-Learning/Elephant-Main#30]
Right now when you login, the elephant client sends a get deck request for each deck the user has, making load times very bad. To fix this, you should be able to call get user request and the decks should be in there, making it so you don't need to call get deck with the long u parse but rather you should parse deck objects from the request. Only send deck get requests if you need to display shared decks.

**Comment by ronakkothari123** [comment]
Should be working 😄
